"""Add silhouette_keypoints to User

Revision ID: 09b183c1fe60
Revises: 8be885c35eae
Create Date: 2026-08-05 23:32:22.008777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09b183c1fe60'
down_revision: Union[str, None] = '8be885c35eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('silhouette_keypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'silhouette_keypoints')
    # ### end Alembic commands ###
