"""Initial tables: users, clothing_items, outfits

Revision ID: 8be885c35eae
Revises: 
Create Date: 2026-08-04 15:03:35.039228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be885c35eae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('silhouette_image_path', sa.String(), nullable=True),
    sa.Column('silhouette_processed_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clothing_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('top', 'bottom', 'dress', 'outerwear', 'shoes', 'accessory', name='clothingcategory'), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_image_path', sa.String(), nullable=False),
    sa.Column('segmented_image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outfit_items',
    sa.Column('outfit_id', sa.UUID(), nullable=False),
    sa.Column('clothing_item_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.PrimaryKeyConstraint('outfit_id', 'clothing_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_items')
    op.drop_table('outfits')
    op.drop_table('clothing_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
